remove zip_entry_t
* inelegant, but it's not required for zip_list
* MZ_ZIP_LOCAL_DIR_HEADER_SIZE is no longer defined in the header and this seems to cause a problem
* likewise mz_zip_writer_add_state
* both are found in miniz.c though
* not sure if they are for internal use now, or somehow are not being seen

zip.c:58:21: error: use of undeclared identifier 'MZ_ZIP_LOCAL_DIR_HEADER_SIZE'
    mz_uint8 header[MZ_ZIP_LOCAL_DIR_HEADER_SIZE];
                    ^
zip.c:61:5: error: unknown type name 'mz_zip_writer_add_state'; did you mean 'mz_zip_internal_state'?
    mz_zip_writer_add_state state;
    ^~~~~~~~~~~~~~~~~~~~~~~
    mz_zip_internal_state
./miniz.h:973:42: note: 'mz_zip_internal_state' declared here
typedef struct mz_zip_internal_state_tag mz_zip_internal_state;
                                         ^
zip.c:61:29: error: field has incomplete type 'mz_zip_internal_state' (aka 'struct mz_zip_internal_state_tag')
    mz_zip_writer_add_state state;
                            ^
./miniz.h:972:8: note: forward declaration of 'struct mz_zip_internal_state_tag'
struct mz_zip_internal_state_tag;
       ^
3 errors generated.